### ISSUE TITLE
return binding.rmdir(pathModule._makeLong(path));

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core-cli#33]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@1.0.3 /home/gordon/Code/storj-bridge
└── storj@4.0.6  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Command

```
set temp=E:\Upload\temp

for /l %%x in (1, 1, 1000) do (
   echo %%x
   storj -k meije0612 -r 12 upload-file 57af3a1e8f266a7d4e391055 D:\films\*   
   TIMEOUT 2
)
```

### Expected Behavior

Upload continues without a problem.

### Actual Behavior

```
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 3c3397a5d70cc75ba65be44e1ab8c357a85a9122 (retry: 20)
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7706d505951b188c3099f5fc622b77b021a7ae (retry: 23)
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 197855865b9f4d48c8d83154d8ca590be7fed20d (retry: 19)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 03df82e044f994ce070c0b43a28dd1b2a8a77e98 (retry: 18)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 587f10289bf9689a7e0d7b43ce31ea8a7cb4e0e9 (retry: 22)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [warn]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Error occurred. Triggering cleanup...
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'E:\Upload\temp\storj-42643fyg19oAh6BR'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:358:10)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:405:10
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:52:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:1209:30
    at UploadState.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:284:9)
    at _handleError (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:513:18)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:547:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:359:16
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:1016:14)
    at self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\request\request.js:187:22)
    at emitOne (events.js:77:13)

Waiting for 0 seconds, press a key to continue ...

```

### Steps to Reproduce

Upload a file.

**Comment by super3** [comment]
I was able to reproduce this when I was uploading a 100 GB test file:

```
$ storj upload-file -k [password] 57fd1cba26adcf743a1adc2c X:\dump100

...

 [Mon Oct 17 2016 19:13:39 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for b3998928697db7d547f14db046f161a3338d2651 (retry: 24)
 [Mon Oct 17 2016 19:13:39 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for ddf7202176cb6ea89de5806f29b60333678d2a5a (retry: 6)
 [Mon Oct 17 2016 19:13:39 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 11873de71069fc221b8f25b1e25afd70f408426c (retry: 16)
 [Mon Oct 17 2016 19:13:42 GMT-0400 (Eastern Daylight Time)] [warn]   Failed to upload shard...
 [Mon Oct 17 2016 19:13:43 GMT-0400 (Eastern Daylight Time)] [warn]   [ dump100 ] Error occurred. Triggering cleanup...
 [Mon Oct 17 2016 19:13:43 GMT-0400 (Eastern Daylight Time)] [info]   [ dump100 ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'X:\temp\storj-16304PFZFMQ745y5T'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:358:10)
    at C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:405:10
    at C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:52:16
    at C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:1209:30
    at UploadState.callback (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:284:9)
    at _handleError (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:506:18)
    at C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:540:16
    at C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:352:16
    at Request._callback (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:1009:14)
    at self.callback (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\storj-lib\node_modules\request\request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

**Comment by MeijeSibbel** [comment]
```
C:\Users\Dani Marion>storj -k meije0612 -r 12 upload-file 57af3a1e8f266a7d4e391055 D:\20GB
 [Tue Oct 18 2016 21:07:49 GMT+0200 (W. Europe Daylight Time)] [info]   1 file(s) to upload.
 [Tue Oct 18 2016 21:07:51 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Tue Oct 18 2016 21:07:51 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/20GB"
 [Tue Oct 18 2016 21:35:37 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Encryption complete
 [Tue Oct 18 2016 21:35:37 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Creating storage token... (retry: 0)
 [Tue Oct 18 2016 21:35:38 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Storing file, hang tight!
 [Tue Oct 18 2016 21:35:39 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\fc955d84a71e index 0
 [Tue Oct 18 2016 21:35:44 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\653896a01310 index 1
 [Tue Oct 18 2016 21:35:45 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 11a47c229e892f51ffea363e7f6518d710b6495a
 [Tue Oct 18 2016 21:35:57 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\20a7549bfa40 index 2
 [Tue Oct 18 2016 21:35:57 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 46b90397b5e801a78f807ab14e6f147be17dca0a
 [Tue Oct 18 2016 21:35:58 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:35:58 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:35:58 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 11a47c229e892f51ffea363e7f6518d710b
6495a (retry: 0)
 [Tue Oct 18 2016 21:36:01 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 11a47c229e892f51ffea363e7f6518d710b
6495a (retry: 1)
 [Tue Oct 18 2016 21:36:03 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.6","protocol":"0.9.1","a
ddress":"cybaer.dyndns.org","port":4000,"nodeID":"1037e361a7a5f0ad918f45a551a9ed85105b3845","lastSeen":1476819353771}
 [Tue Oct 18 2016 21:36:04 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:36:10 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\97a4d6cab1c2 index 3
 [Tue Oct 18 2016 21:36:10 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:36:10 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:36:10 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 46b90397b5e801a78f807ab14e6f147be17
dca0a (retry: 0)
 [Tue Oct 18 2016 21:36:10 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 8e82cb5c94a61e50e5f43f64d3cc0b1e2ea83f91
 [Tue Oct 18 2016 21:36:13 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 46b90397b5e801a78f807ab14e6f147be17
dca0a (retry: 1)
 [Tue Oct 18 2016 21:36:15 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","a
ddress":"016s.storjlt.xyz","port":4301,"nodeID":"94bc2d51ede0a3a1b5970686acbf32933474bf2c","lastSeen":1476819366841}
 [Tue Oct 18 2016 21:36:15 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:36:24 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\d78b32c3e6cc index 4
 [Tue Oct 18 2016 21:36:24 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 361347dfaa887a7de40c2fc4c6cadea260273a09
 [Tue Oct 18 2016 21:36:24 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:36:24 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:36:24 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 8e82cb5c94a61e50e5f43f64d3cc0b1e2ea
83f91 (retry: 0)
 [Tue Oct 18 2016 21:36:27 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.6","protocol":"0.9.1","a
ddress":"sj4.cybaer.dyndns.org","port":4020,"nodeID":"c7e8e45d741092ff84b73178d13a4e6a5b68349d","lastSeen":1476819377959}
 [Tue Oct 18 2016 21:36:28 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:36:39 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\31463062b58b index 5
 [Tue Oct 18 2016 21:36:39 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: f847afea960177e00a8a0badaa7b8a3986f52f8e
 [Tue Oct 18 2016 21:36:39 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:36:39 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:36:39 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 361347dfaa887a7de40c2fc4c6cadea2602
73a09 (retry: 0)
 [Tue Oct 18 2016 21:36:40 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.6","protocol":"0.9.1","a
ddress":"STORJ-CLUS-039.storj.space","port":4000,"nodeID":"fa162cf25be8a9d474b27dc37cd080b4ad3e6b9c","lastSeen":1476819391875}
 [Tue Oct 18 2016 21:36:40 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:36:54 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: f5414665904f9652ba14ae70b6fd2bc1056fa78d
 [Tue Oct 18 2016 21:36:54 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:36:54 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:36:54 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f847afea960177e00a8a0badaa7b8a3986f
52f8e (retry: 0)
 [Tue Oct 18 2016 21:36:56 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.5","protocol":"0.9.1","a
ddress":"80.237.71.105","port":6240,"nodeID":"72de8e9bf524fb09b54a03cf648facfbbe8d514c","lastSeen":1476819407770}
 [Tue Oct 18 2016 21:36:57 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:37:09 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Oct 18 2016 21:37:09 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Oct 18 2016 21:37:09 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f5414665904f9652ba14ae70b6fd2bc1056
fa78d (retry: 0)
 [Tue Oct 18 2016 21:37:12 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f5414665904f9652ba14ae70b6fd2bc1056
fa78d (retry: 1)
 [Tue Oct 18 2016 21:37:15 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f5414665904f9652ba14ae70b6fd2bc1056
fa78d (retry: 2)
 [Tue Oct 18 2016 21:37:18 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f5414665904f9652ba14ae70b6fd2bc1056
fa78d (retry: 3)
 [Tue Oct 18 2016 21:37:21 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f5414665904f9652ba14ae70b6fd2bc1056
fa78d (retry: 4)
 [Tue Oct 18 2016 21:37:23 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.6","protocol":"0.9.1","a
ddress":"131.191.69.164","port":38068,"nodeID":"c773d0761b6c1511284be3e42d71338eb2517521","lastSeen":1476819434199}
 [Tue Oct 18 2016 21:37:23 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Oct 18 2016 21:37:36 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-8184ax4B8Hy7cNfw'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:2
85:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:
5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:3
58:10)
    at null.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:381:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Monitor.sendEvent (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-moni
tor.js:72:8)
    at cycle (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:116:1
2)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\Dani Marion>
```

**Comment by MeijeSibbel** [comment]
Some fresh errors below, i don't know if this is a coincidence or not but i get these errors at the same time i get the 'not enough memory to proceed' error in core-CLI.


```
echo 4
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\Pictures\*  1>>D:\instance3.log
 TIMEOUT 2
)
4
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-7008qmGCntxnryDI'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:381:10)
    at null.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:404:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Monitor.sendEvent (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:72:8)
    at cycle (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:116:12)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 5
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\Pictures\*  1>>D:\instance3.log
 TIMEOUT 2
)
5
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-1172EcJ48Hayd9mx'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:381:10)
    at null.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\bin\actions\uploader.js:404:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Monitor.sendEvent (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:72:8)
    at cycle (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:116:12)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 6
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\Pictures\*  1>>D:\instance3.log
 TIMEOUT 2
)
6

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 7
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\Pictures\*  1>>D:\instance3.log
 TIMEOUT 2
)
7

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 8
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\Pictures\*  1>>D:\instance3.log
 TIMEOUT 2
)
8
```
