### ISSUE TITLE
Mirroring 100MB+ Returns ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by super3** [Storj/core-cli#46]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
Storjcli: 1.0.17 | Core: 4.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior

Tell me I've established mirrors. 
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storj upload-file -k [password] -r 6 -c 3 57fd1cba26adcf743a1adc2c upfile
...
 [Thu Oct 27 2016 11:19:09 GMT-0400 (EDT)] [info]   Contract negotiated with: {"userAgent":"4.1.0","protocol":"0.9.1","address":"67.175.37.210","port":8443,"nodeID":"da2e0fd632eed06894e025f3ec72e14e8d2ed0dc","lastSeen":1477581549443}
 [Thu Oct 27 2016 11:19:09 GMT-0400 (EDT)] [info]   Data channel opened, transferring shard...
 [Thu Oct 27 2016 11:19:10 GMT-0400 (EDT)] [info]   Shard transfer completed! 2 remaining...
 [Thu Oct 27 2016 11:19:11 GMT-0400 (EDT)] [info]   Querying bridge for contract for 16988a9fd641d0ef033790162d148d8cd2c3f305 (retry: 1)
 [Thu Oct 27 2016 11:19:12 GMT-0400 (EDT)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"37.97.185.28","port":4100,"nodeID":"0f77a4ce2c34ff7d3e121bc5ac065a12589a9f3a","lastSeen":1477581552291}
 [Thu Oct 27 2016 11:19:12 GMT-0400 (EDT)] [info]   Data channel opened, transferring shard...
 [Thu Oct 27 2016 11:19:14 GMT-0400 (EDT)] [info]   Shard transfer completed! 1 remaining...
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   Shard transfer completed! 0 remaining...
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   Transfer finished, creating entry.. (retry: 0)
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   [ (2016-10-27T15;18;41.390Z)-upfile ] Cleaning up...
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   [ (2016-10-27T15;18;41.390Z)-upfile ] Finished cleaning!
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   [ (2016-10-27T15;18;41.390Z)-upfile ] Encryption key saved to keyring.
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   [ (2016-10-27T15;18;41.390Z)-upfile ] File successfully stored in bucket.
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   Name: (2016-10-27T15;18;41.390Z)-upfile, Type: application/octet-stream, Size: 104857600 bytes, ID: 0bf8d0d88440d25e85f4f68d
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Thu Oct 27 2016 11:19:21 GMT-0400 (EDT)] [info]   Done.
 [Thu Oct 27 2016 11:19:31 GMT-0400 (EDT)] [error]  ESOCKETTIMEDOUT
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Mirroring works with 1 MB.
2. Mirroring works with 10 MB.
3. Gives a ESOCKETTIMEDOUT on 100 MB upload.

**Comment by super3** [comment]
Also see this error:
```
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   [ (2016-10-27T16;12;42.228Z)-upfile ] Encryption key saved to keyring.
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   [ (2016-10-27T16;12;42.228Z)-upfile ] File successfully stored in bucket.
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   Name: (2016-10-27T16;12;42.228Z)-upfile, Type: application/octet-stream, Size: 117440512 bytes, ID: a7cb6b0ea4d9c23489a19d59
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   Done.
 [Thu Oct 27 2016 12:13:31 GMT-0400 (EDT)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:62:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:87:13)<br> &nbsp; &nbsp;at Request.emit (events.js:172:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:1060:10)<br> &nbsp; &nbsp;at emitOne (events.js:77:13)<br> &nbsp; &nbsp;at Request.emit (events.js:169:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:980:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:260:16)<br> &nbsp; &nbsp;at emitNone (events.js:72:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)
```

**Comment by MeijeSibbel** [comment]
@super3, I already opened a issue for the no shard data found: https://github.com/Storj/bridge/issues/261

**Comment by super3** [comment]
@MeijeSibbel This is a separate issue it looks like: https://github.com/Storj/complex/issues/16

**Comment by vevarm** [comment]
Also this error: key not found.  

Sat Nov 19 2016 22:14:03 GMT+0100 (CET)] [error]  Error: Key not found in database [4579c674a30a20b880712bcd636b4aa2dacd5f79]<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:61:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:106:13)<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/request/request.js:1081:10)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/request/request.js:1001:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)
