### ISSUE TITLE
Upload Command Will Not Terminate

### ISSUE THREAD

**Issue by super3** [Storj/core-cli#50]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storjcli: 1.0.17 | Core: 4.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Upload command exits. 

### Actual Behavior

I have a collection of upload scripts that run the following command:

 ```
storj upload-file -k  <password> -r 3 -c 3 57fd1cba26adcf743a1adc2c upfile
```

It is currently November 1st, but it looks like the CLI encountered an error on the 30th, and the CLI never exited. 

#### Upload 1

```
 [Sun Oct 30 2016 22:33:06 GMT-0400 (EDT)] [info]   Name: (2016-10-31T02;32;17.547Z)-upfile, Type: application/octet-stream, Size: 113246208 bytes, ID: 870798ef8c536f8080ab6672
 [Sun Oct 30 2016 22:33:06 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Sun Oct 30 2016 22:33:06 GMT-0400 (EDT)] [info]   Done.
 [Sun Oct 30 2016 22:33:16 GMT-0400 (EDT)] [error]  ESOCKETTIMEDOUT
```

#### Upload 2

```
 [Sat Oct 29 2016 17:19:35 GMT-0400 (EDT)] [info]   [ (2016-10-29T21;17;59.589Z)-upfile2 ] Encryption key saved to keyring.
 [Sat Oct 29 2016 17:19:35 GMT-0400 (EDT)] [info]   [ (2016-10-29T21;17;59.589Z)-upfile2 ] File successfully stored in bucket.
 [Sat Oct 29 2016 17:19:35 GMT-0400 (EDT)] [info]   Name: (2016-10-29T21;17;59.589Z)-upfile2, Type: application/octet-stream, Size: 121634816 bytes, ID: a1107178a0ab6139bfb1a0a3
 [Sat Oct 29 2016 17:19:35 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Sat Oct 29 2016 17:19:35 GMT-0400 (EDT)] [info]   Done.
 [Sat Oct 29 2016 17:19:40 GMT-0400 (EDT)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:62:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:87:13)<br> &nbsp; &nbsp;at Request.emit (events.js:172:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:1060:10)<br> &nbsp; &nbsp;at emitOne (events.js:77:13)<br> &nbsp; &nbsp;at Request.emit (events.js:169:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:980:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:260:16)<br> &nbsp; &nbsp;at emitNone (events.js:72:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)
```

#### Upload 3

```
 [Sun Oct 30 2016 12:22:45 GMT-0400 (EDT)] [info]   [ (2016-10-30T16;21;28.161Z)-upfile3 ] File successfully stored in bucket.
 [Sun Oct 30 2016 12:22:45 GMT-0400 (EDT)] [info]   Name: (2016-10-30T16;21;28.161Z)-upfile3, Type: application/octet-stream, Size: 113246208 bytes, ID: 0622258616d5c7bded1a0038
 [Sun Oct 30 2016 12:22:45 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Sun Oct 30 2016 12:22:45 GMT-0400 (EDT)] [info]   Done.
 [Sun Oct 30 2016 12:22:55 GMT-0400 (EDT)] [error]  ESOCKETTIMEDOUT
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run an upload script for a couple of days. 
2. An error will occur and the script will never terminate.

**Comment by super3** [comment]
@aleitner The strange this is that I can't always reproduce this. Only happens after leaving it alone for a few days. I have gotten many logs that end with `ESOCKETTIMEDOUT`, but it will exit and continue to upload.
