### ISSUE TITLE
Login Returns a Keypath is not a Function

### ISSUE THREAD

**Issue by super3** [Storj/core-cli#55]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
tester@super3-sandbox:~$ npm list -g storj
/home/tester/.nvm/versions/node/v6.9.1/lib
└── storj@4.0.1
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Able to login.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
tester@super3-sandbox:~$ storj login
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/account.js:46
  if (storj.utils.existsSync(self._storj.keypath())) {
                                         ^

TypeError: self._storj.keypath is not a function
    at Command.module.exports.login (/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/account.js:46:42)
    at Command.listener (/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/commander/index.js:615:12)
    at Command.parse (/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/tester/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/storj.js:402:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

2. Install Storj and try to login

**Comment by super3** [comment]
Was able to reproduce this on 4.5.0
