### ISSUE TITLE
[UNHANDLED ERROR] TypeError: fileName.replace is not a function

### ISSUE THREAD

**Issue by lakewik** [Storj/core-cli#61]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/home/lakewik/.nvm/versions/node/v4.4.4/lib
└── storj@4.0.1

```
storj --version
```
Storjcli: 2.0.1 | Core: 5.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I'm able to download file
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
NOTE: I'm using apipool001.storj.dk bridge
Logs from downloading file:

storj download-file --debug  --url http://apipool001.storj.dk 158d9e45c8860293a218c8d3  e43388b8bbb7d26267c7f336 test14.flv
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [Sat Nov 12 2016 10:56:32 GMT+0100 (CET)] [debug]  Parameter for ECDSA signature: GET\n/buckets/158d9e45c8860293a218c8d3/files/e43388b8bbb7d26267c7f336/info\n__nonce=17dc4b51-a5d9-4d96-8045-fd696711bfe4
 [Sat Nov 12 2016 10:56:32 GMT+0100 (CET)] [debug]  Request: {"baseUrl":"http://apipool001.storj.dk","uri":"/buckets/158d9e45c8860293a218c8d3/files/e43388b8bbb7d26267c7f336/info","method":"GET","timeout":10000,"qs":{"__nonce":"17dc4b51-a5d9-4d96-8045-fd696711bfe4"},"json":true,"headers":{"x-pubkey":"02c1caa6bb04861ab1f148abf488bf0cbbabe659c3315134cc47a2015aed6ec501","x-signature":"3045022100968fd8785c50b64720001c87ab97a92f8cfe0d8d82bf55300df0507d297aca9a02207d9aaac94438410d194a033ab2c1f8fb50313d73e20498cf4cda2db3748e051f"}}
 [Sat Nov 12 2016 10:56:32 GMT+0100 (CET)] [debug]  Body: {"bucket":"158d9e45c8860293a218c8d3","mimetype":"video/x-flv","filename":{"_id":"5826e2cf82e495047ad9cf8d","user":"wikjezioro@op.pl","__v":7,"shards":["5826e2d0bc2f6cb01c7e2056","5826e2d08f64ce7c343e07d0","5826e3392f64621713c150bd"],"size":41006321,"locked":true,"created":"2016-11-12T09:37:19.561Z"},"frame":"5826e2cf82e495047ad9cf8d","size":41006321,"id":"e43388b8bbb7d26267c7f336"}
 [Sat Nov 12 2016 10:56:32 GMT+0100 (CET)] [info]   Name: [object Object], Type: video/x-flv, Size: 41006321 bytes, ID: e43388b8bbb7d26267c7f336
/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-cli/bin/actions/downloader.js:74
  return fileName.replace(re, '');
                  ^

TypeError: fileName.replace is not a function
    at Downloader._stripISOString (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-cli/bin/actions/downloader.js:74:19)
    at /home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-cli/bin/actions/downloader.js:94:35
    at Request._callback (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-lib/lib/bridge-client/index.js:1061:5)
    at Request.self.callback (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-lib/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-lib/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/storj-lib/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Download file using apipool001.storj.dk bridge

**Comment by bookchin** [comment]
https://github.com/Storj/service-storage-models/pull/24
