### ISSUE TITLE
[UNHANDLED ERROR] read ECONNRESET

### ISSUE THREAD

**Issue by lakewik** [Storj/core-cli#76]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.
```
/home/lakewik/.nvm/versions/node/v6.9.1/lib
└── storj@4.0.1
```
storj --version
```
Storjcli: 3.1.0 | Core: 6.0.4
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Should retry when this error happens.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Crash after ECONNRESET:

Log:
 [Sat Dec 10 2016 11:59:15 GMT+0100 (CET)] [info]   Trying to upload shard /tmp/02c508c3bb66 index 0
 [Sat Dec 10 2016 11:59:15 GMT+0100 (CET)] [info]   Hash for this shard is: 63e070f67b7cb88229267099e5665e45827a5121
 [Sat Dec 10 2016 11:59:15 GMT+0100 (CET)] [info]   Audit generation for shard done.
 [Sat Dec 10 2016 11:59:15 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Sat Dec 10 2016 11:59:15 GMT+0100 (CET)] [info]   Querying bridge for contract for 63e070f67b7cb88229267099e5665e45827a5121 (retry: 0)
 [Sat Dec 10 2016 11:59:18 GMT+0100 (CET)] [info]   Contract negotiated with: {"userAgent":"6.0.4","protocol":"1.0.0","address":"71.223.22.111","port":12562,"nodeID":"61e7d7e74a36067b6875b02e1ae59e06629eebbe","lastSeen":1481367557602}
 [Sat Dec 10 2016 11:59:45 GMT+0100 (CET)] [warn]   Failed to transfer shard, reason: 
 [Sat Dec 10 2016 11:59:45 GMT+0100 (CET)] [info]   Shard transfer failed 0 times, getting another contract...
 [Sat Dec 10 2016 11:59:45 GMT+0100 (CET)] [info]   Hash for this shard is: 63e070f67b7cb88229267099e5665e45827a5121
 [Sat Dec 10 2016 11:59:45 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Sat Dec 10 2016 11:59:45 GMT+0100 (CET)] [info]   Querying bridge for contract for 63e070f67b7cb88229267099e5665e45827a5121 (retry: 0)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a lot of files
2. Probably you see this error

**Comment by deadgray** [comment]
storjshare -V
StorjShare: 9.0.3
Core:       6.0.5
Protocol:   1.0.0

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

```

Error comes after some time of running storjshare-cli.

**Comment by braydonf** [comment]
Related:
- https://github.com/Storj/storjshare-cli/issues/234
- https://github.com/Storj/storjshare-gui/issues/466

**Comment by tamchik** [comment]
{warn} [Wed Dec 14 2016 16:57:13 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:57:43 GMT+0100 (W. Europe Standard Time)] rpc call 54db1e93f6d834a68d517e188f2d78c2d37ba18b timed out
{warn} [Wed Dec 14 2016 16:58:02 GMT+0100 (W. Europe Standard Time)] you are not publicly reachable, trying traversal strategies...
{warn} [Wed Dec 14 2016 16:58:04 GMT+0100 (W. Europe Standard Time)] could not connect to NAT device via UPnP: 64177
{warn} [Wed Dec 14 2016 16:58:23 GMT+0100 (W. Europe Standard Time)] error returned from remote host: {"error":"Unable to route to tunnel, client is not connected"}
{warn} [Wed Dec 14 2016 16:58:23 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:58:23 GMT+0100 (W. Europe Standard Time)] error returned from remote host: {"error":"Unable to route to tunnel, client is not connected"}
{warn} [Wed Dec 14 2016 16:58:23 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:58:44 GMT+0100 (W. Europe Standard Time)] error returned from remote host: connect EADDRNOTAVAIL 0.0.0.0:52887
{warn} [Wed Dec 14 2016 16:58:44 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] rpc call 43903c3c69fa050d16c7637bba0af9acad450e0f timed out
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] failed to get neighbor's bloom filter, reason: RPC with ID `43903c3c69fa050d16c7637bba0af9acad450e0f` timed out
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] rpc call b81dd7c7c72381686850ca74c85570254be88043 timed out
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] failed to get neighbor's bloom filter, reason: RPC with ID `b81dd7c7c72381686850ca74c85570254be88043` timed out
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] rpc call 9d02127aa6c3df67171bf02e79c2fb1a7c361a5e timed out
{warn} [Wed Dec 14 2016 16:58:47 GMT+0100 (W. Europe Standard Time)] query failed, removing contact for shortlist, reason RPC with ID `9d02127aa6c3df67171bf02e79c2fb1a7c361a5e` timed out
{warn} [Wed Dec 14 2016 16:58:48 GMT+0100 (W. Europe Standard Time)] error returned from remote host: {"error":"Unable to route to tunnel, client is not connected"}
{warn} [Wed Dec 14 2016 16:58:48 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:58:48 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact
{warn} [Wed Dec 14 2016 16:58:48 GMT+0100 (W. Europe Standard Time)] error returned from remote host: {"error":"Unable to route to tunnel, client is not connected"}
{warn} [Wed Dec 14 2016 16:58:55 GMT+0100 (W. Europe Standard Time)] error returned from remote host: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

{warn} [Wed Dec 14 2016 16:58:55 GMT+0100 (W. Europe Standard Time)] missing or empty reply from contact

**Comment by braydonf** [comment]
@tamchik What's the relevance?

**Comment by tamchik** [comment]
true that the number of contracts is not updated, the log is filtered by errors and warnig's

**Comment by MeijeSibbel** [comment]
```
[Sun Jan 22 2017 02:40:30 GMT+0100 (W. Europe Standard Time)] [info]   Audit generation for shard done.
 [Sun Jan 22 2017 02:40:30 GMT+0100 (W. Europe Standard Time)] [info]   Waiting on a storage offer from the network...
 [Sun Jan 22 2017 02:40:30 GMT+0100 (W. Europe Standard Time)] [info]   Querying bridge for contract for b7b0095e6c38128c833003244beaa89c53ee5214 (retry: 0)
 [Sun Jan 22 2017 02:40:32 GMT+0100 (W. Europe Standard Time)] [info]   Contract negotiated with: {"userAgent":"6.0.12","protocol":"1.0.0","address":"98.27.222.254","port"
:4000,"nodeID":"b692cf937543fcdfeb956274261feab3b8fa3c6f","lastSeen":1485049224138}
 [Sun Jan 22 2017 02:41:04 GMT+0100 (W. Europe Standard Time)] [warn]   Failed to transfer shard, reason: write ECONNRESET
 [Sun Jan 22 2017 02:41:04 GMT+0100 (W. Europe Standard Time)] [info]   Shard transfer failed 0 times, getting another contract...
 [Sun Jan 22 2017 02:41:04 GMT+0100 (W. Europe Standard Time)] [info]   Adding NodeID b692cf937543fcdfeb956274261feab3b8fa3c6f to blacklist
 [Sun Jan 22 2017 02:41:05 GMT+0100 (W. Europe Standard Time)] [info]   Hash for this shard is: b7b0095e6c38128c833003244beaa89c53ee5214
 [Sun Jan 22 2017 02:41:05 GMT+0100 (W. Europe Standard Time)] [info]   Waiting on a storage offer from the network...
 [Sun Jan 22 2017 02:41:05 GMT+0100 (W. Europe Standard Time)] [info]   Querying bridge for contract for b7b0095e6c38128c833003244beaa89c53ee5214 (retry: 0)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)

Waiting for 0 seconds, press a key to continue ...
```

**Comment by MeijeSibbel** [comment]
```
 [Thu Feb 23 2017 23:57:22 GMT+0100 (W. Europe Standard Time)] [warn]   Failed to transfer shard, reason: write ECONNRESET
 [Thu Feb 23 2017 23:57:22 GMT+0100 (W. Europe Standard Time)] [info]   Shard transfer failed 0 times, getting another contract...
 [Thu Feb 23 2017 23:57:22 GMT+0100 (W. Europe Standard Time)] [info]   Adding NodeID 283cb17aad9c69acc4fc732f29530e28a7ecb8bc to blacklist
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
```
