### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by lakewik** [Storj/core-cli#84]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/home/lakewik/.nvm/versions/node/v6.9.1/lib
└── storj@4.0.
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
No errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.
Occurs unhandled EPIPE error.

```
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Shard transfer completed! 44 remaining...
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Trying to upload shard /tmp/97d330d69119 index 98
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   sending exchange report
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Hash for this shard is: c511818f15ae43c5562e04255ffe95572a10df19
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Audit generation for shard done.
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Tue Jan 03 2017 21:30:37 GMT+0100 (CET)] [info]   Querying bridge for contract for c511818f15ae43c5562e04255ffe95572a10df19 (retry: 0)
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Shard transfer completed! 43 remaining...
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Trying to upload shard /tmp/d4abedecbe80 index 99
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   sending exchange report
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Hash for this shard is: 87f72d9e5c6cd5bc0e61bdf961400513311c9673
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Audit generation for shard done.
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Tue Jan 03 2017 21:30:39 GMT+0100 (CET)] [info]   Querying bridge for contract for 87f72d9e5c6cd5bc0e61bdf961400513311c9673 (retry: 0)
 [Tue Jan 03 2017 21:30:40 GMT+0100 (CET)] [info]   Contract negotiated with: {"userAgent":"6.0.11","protocol":"1.0.0","address":"73.43.5.80","port":12573,"nodeID":"c53b22ab91ed61c49a3c1816265e10d0ac01b52c","lastSeen":1483475440322}
 [Tue Jan 03 2017 21:30:43 GMT+0100 (CET)] [info]   Contract negotiated with: {"userAgent":"6.0.11","protocol":"1.0.0","address":"client017.storj.dk","port":15004,"nodeID":"84c4a828968a1ae5b57f5c2d725f0a9124472a06","lastSeen":1483475442483}
 [Tue Jan 03 2017 21:30:43 GMT+0100 (CET)] [info]   Shard transfer completed! 42 remaining...
 [Tue Jan 03 2017 21:30:43 GMT+0100 (CET)] [info]   Trying to upload shard /tmp/8d7cb619a8f4 index 100
 [Tue Jan 03 2017 21:30:43 GMT+0100 (CET)] [info]   sending exchange report
 [Tue Jan 03 2017 21:30:43 GMT+0100 (CET)] [info]   Hash for this shard is: 07306aa1f62c28d2195db7733bc121f4afaa8c9a
 [Tue Jan 03 2017 21:30:44 GMT+0100 (CET)] [info]   Audit generation for shard done.
 [Tue Jan 03 2017 21:30:44 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Tue Jan 03 2017 21:30:44 GMT+0100 (CET)] [info]   Querying bridge for contract for 07306aa1f62c28d2195db7733bc121f4afaa8c9a (retry: 0)
 [Tue Jan 03 2017 21:30:47 GMT+0100 (CET)] [info]   Contract negotiated with: {"userAgent":"6.0.11","protocol":"1.0.0","address":"002s.storjlt.xyz","port":8601,"nodeID":"076c32b0f81bba232e4b09052cc54517a7921945","lastSeen":1483475447511}
 [Tue Jan 03 2017 21:30:55 GMT+0100 (CET)] [warn]   Failed to transfer shard, reason: 
 [Tue Jan 03 2017 21:30:55 GMT+0100 (CET)] [info]   Shard transfer failed 0 times, getting another contract...
 [Tue Jan 03 2017 21:30:55 GMT+0100 (CET)] [info]   Hash for this shard is: cabfb5ebae67c2ab96959bf7f56d199d22d96e20
 [Tue Jan 03 2017 21:30:55 GMT+0100 (CET)] [info]   Waiting on a storage offer from the network...
 [Tue Jan 03 2017 21:30:55 GMT+0100 (CET)] [info]   Querying bridge for contract for cabfb5ebae67c2ab96959bf7f56d199d22d96e20 (retry: 0)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload big file
2. Error occuring randomly

**Comment by CJClaude** [comment]
Just another data point.

 [Fri Jan 20 2017 19:33:19 GMT-0600 (CST)] [info]   Contract negotiated with: {"userAgent":"6.0.11","protocol":"1.0.0","address":"62.65.221.96","port":4002,"nodeID":"b2de465b4be9a2ea1e631cb1e190700cf63b95d1","lastSeen":1484962398793}
 [Fri Jan 20 2017 19:33:22 GMT-0600 (CST)] [info]   Contract negotiated with: {"userAgent":"6.0.11","protocol":"1.0.0","address":"74.133.3.15","port":4100,"nodeID":"2e63ffb510ad8270f5d14b9bf952d5d75f3c0124","lastSeen":1484962402311}
 [Fri Jan 20 2017 19:33:26 GMT-0600 (CST)] [warn]   Request failed, reason: ETIMEDOUT - retrying(true)...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)
i5serv ~ #
